export const FETCHING_COURSE = "FETCHING_COURSE";
export const FETCHING_COURSE_SUCCESS = "FETCHING_COURSE_SUCCESS";
export const FETCHING_COURSE_FAIL = "FETCHING_COURSE_FAIL";

export const FETCHING_REVIEWS = "FETCHING_REVIEWS";
export const FETCHING_REVIEWS_SUCCESS = "FETCHING_REVIEWS_SUCCESS";
export const FETCHING_REVIEWS_FAIL = "FETCHING_REVIEWS_FAIL";

export const FETCHING_CREATE_REVIEW = "FETCHING_CREATE_REVIEW";
export const FETCHING_CREATE_REVIEW_SUCCESS = "FETCHING_CREATE_REVIEW_SUCCESS";
export const FETCHING_CREATE_REVIEW_FAIL = "FETCHING_CREATE_REVIEW_FAIL";