export const FETCHING_LOGIN = "FETCHING_LOGIN";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FETCHING_LOGOUT = "FETCHING_LOGOUT";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const FETCHING_SIGNUP = "FETCHING_SIGNUP";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
export const SIGNUP_FAIL = "SIGNUP_FAIL";