export const SET_PROFILE = "SET_PROFILE";
export const FETCHING_PROFILE = "FETCHING_PROFILE";
export const FETCHING_PROFILE_SUCCESS = "FETCHING_PROFILE_SUCCESS";
export const FETCHING_PROFILE_FAIL = "FETCHING_PROFILE_FAIL";